### ISSUE TITLE
CocoaPods spec problem

### ISSUE THREAD

**Issue by dhilowitz** [michalkonturek/MKDevice#1]
When I try to use CocoaPods to install the library, it installs version 0.0.3, which is fairly old. It also installs the latest version of the MKFoundationKit library (1.3.0) which is incompatible with version 0.0.3 of this library.

--Dave

**Comment by michalkonturek** [comment]
Hi David, 

Version 0.0.3 is the only version that is available via pods. I have not done any work on this project for about 6 months. Looking at the commits, there are no significant changes when it comes to functionality.

I have investigated your issue with MKFoundationKit library and did not see any problems. Could you please elaborate on this matter?
